// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feedmessage.proto

package com.tid.protojson;

public final class Feedmessage {
  private Feedmessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(com.tid.protojson.Feedmessage.source);
    registry.add(com.tid.protojson.Feedmessage.d);
    registry.add(com.tid.protojson.Feedmessage.f);
    registry.add(com.tid.protojson.Feedmessage.i32);
    registry.add(com.tid.protojson.Feedmessage.i64);
    registry.add(com.tid.protojson.Feedmessage.ui32);
    registry.add(com.tid.protojson.Feedmessage.ui64);
    registry.add(com.tid.protojson.Feedmessage.si32);
    registry.add(com.tid.protojson.Feedmessage.si64);
    registry.add(com.tid.protojson.Feedmessage.f32);
    registry.add(com.tid.protojson.Feedmessage.f64);
    registry.add(com.tid.protojson.Feedmessage.verdad);
    registry.add(com.tid.protojson.Feedmessage.s);
    registry.add(com.tid.protojson.Feedmessage.bites);
  }
  public interface UserOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string uuid = 1;
    boolean hasUuid();
    String getUuid();
    
    // required string domain = 2;
    boolean hasDomain();
    String getDomain();
    
    // optional int32 number = 8;
    boolean hasNumber();
    int getNumber();
  }
  public static final class User extends
      com.google.protobuf.GeneratedMessage
      implements UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(Builder builder) {
      super(builder);
    }
    private User(boolean noInit) {}
    
    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_User_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_User_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string uuid = 1;
    public static final int UUID_FIELD_NUMBER = 1;
    private Object uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getUuid() {
      Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uuid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUuidBytes() {
      Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string domain = 2;
    public static final int DOMAIN_FIELD_NUMBER = 2;
    private Object domain_;
    public boolean hasDomain() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDomain() {
      Object ref = domain_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          domain_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDomainBytes() {
      Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 number = 8;
    public static final int NUMBER_FIELD_NUMBER = 8;
    private int number_;
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getNumber() {
      return number_;
    }
    
    private void initFields() {
      uuid_ = "";
      domain_ = "";
      number_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDomain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDomainBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(8, number_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUuidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDomainBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, number_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tid.protojson.Feedmessage.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tid.protojson.Feedmessage.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tid.protojson.Feedmessage.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tid.protojson.Feedmessage.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tid.protojson.Feedmessage.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_User_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_User_fieldAccessorTable;
      }
      
      // Construct using com.tid.protojson.Feedmessage.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        domain_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tid.protojson.Feedmessage.User.getDescriptor();
      }
      
      public com.tid.protojson.Feedmessage.User getDefaultInstanceForType() {
        return com.tid.protojson.Feedmessage.User.getDefaultInstance();
      }
      
      public com.tid.protojson.Feedmessage.User build() {
        com.tid.protojson.Feedmessage.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tid.protojson.Feedmessage.User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tid.protojson.Feedmessage.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tid.protojson.Feedmessage.User buildPartial() {
        com.tid.protojson.Feedmessage.User result = new com.tid.protojson.Feedmessage.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.domain_ = domain_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.number_ = number_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tid.protojson.Feedmessage.User) {
          return mergeFrom((com.tid.protojson.Feedmessage.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tid.protojson.Feedmessage.User other) {
        if (other == com.tid.protojson.Feedmessage.User.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasDomain()) {
          setDomain(other.getDomain());
        }
        if (other.hasNumber()) {
          setNumber(other.getNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUuid()) {
          
          return false;
        }
        if (!hasDomain()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              uuid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              domain_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000004;
              number_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string uuid = 1;
      private Object uuid_ = "";
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getUuid() {
        Object ref = uuid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      void setUuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
      }
      
      // required string domain = 2;
      private Object domain_ = "";
      public boolean hasDomain() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDomain() {
        Object ref = domain_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDomain(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        domain_ = value;
        onChanged();
        return this;
      }
      public Builder clearDomain() {
        bitField0_ = (bitField0_ & ~0x00000002);
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      void setDomain(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        domain_ = value;
        onChanged();
      }
      
      // optional int32 number = 8;
      private int number_ ;
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getNumber() {
        return number_;
      }
      public Builder setNumber(int value) {
        bitField0_ |= 0x00000004;
        number_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        number_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.tid.protojson.User)
    }
    
    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.tid.protojson.User)
  }
  
  public interface EntryOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<Entry> {
    
    // required int32 id = 1;
    boolean hasId();
    int getId();
    
    // optional .com.tid.protojson.User author = 4;
    boolean hasAuthor();
    com.tid.protojson.Feedmessage.User getAuthor();
    com.tid.protojson.Feedmessage.UserOrBuilder getAuthorOrBuilder();
    
    // optional string link = 5;
    boolean hasLink();
    String getLink();
    
    // optional int32 updated = 6;
    boolean hasUpdated();
    int getUpdated();
    
    // optional int32 publised = 7;
    boolean hasPublised();
    int getPublised();
    
    // optional .com.tid.protojson.User owner = 8;
    boolean hasOwner();
    com.tid.protojson.Feedmessage.User getOwner();
    com.tid.protojson.Feedmessage.UserOrBuilder getOwnerOrBuilder();
  }
  public static final class Entry extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        Entry> implements EntryOrBuilder {
    // Use Entry.newBuilder() to construct.
    private Entry(Builder builder) {
      super(builder);
    }
    private Entry(boolean noInit) {}
    
    private static final Entry defaultInstance;
    public static Entry getDefaultInstance() {
      return defaultInstance;
    }
    
    public Entry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_Entry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_Entry_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getId() {
      return id_;
    }
    
    // optional .com.tid.protojson.User author = 4;
    public static final int AUTHOR_FIELD_NUMBER = 4;
    private com.tid.protojson.Feedmessage.User author_;
    public boolean hasAuthor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.tid.protojson.Feedmessage.User getAuthor() {
      return author_;
    }
    public com.tid.protojson.Feedmessage.UserOrBuilder getAuthorOrBuilder() {
      return author_;
    }
    
    // optional string link = 5;
    public static final int LINK_FIELD_NUMBER = 5;
    private Object link_;
    public boolean hasLink() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getLink() {
      Object ref = link_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          link_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLinkBytes() {
      Object ref = link_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        link_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 updated = 6;
    public static final int UPDATED_FIELD_NUMBER = 6;
    private int updated_;
    public boolean hasUpdated() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getUpdated() {
      return updated_;
    }
    
    // optional int32 publised = 7;
    public static final int PUBLISED_FIELD_NUMBER = 7;
    private int publised_;
    public boolean hasPublised() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getPublised() {
      return publised_;
    }
    
    // optional .com.tid.protojson.User owner = 8;
    public static final int OWNER_FIELD_NUMBER = 8;
    private com.tid.protojson.Feedmessage.User owner_;
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public com.tid.protojson.Feedmessage.User getOwner() {
      return owner_;
    }
    public com.tid.protojson.Feedmessage.UserOrBuilder getOwnerOrBuilder() {
      return owner_;
    }
    
    private void initFields() {
      id_ = 0;
      author_ = com.tid.protojson.Feedmessage.User.getDefaultInstance();
      link_ = "";
      updated_ = 0;
      publised_ = 0;
      owner_ = com.tid.protojson.Feedmessage.User.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAuthor()) {
        if (!getAuthor().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasOwner()) {
        if (!getOwner().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<com.tid.protojson.Feedmessage.Entry>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(4, author_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(5, getLinkBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(6, updated_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(7, publised_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(8, owner_);
      }
      extensionWriter.writeUntil(21, output);
      extensionWriter.writeUntil(31, output);
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, author_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getLinkBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, updated_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, publised_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, owner_);
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tid.protojson.Feedmessage.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tid.protojson.Feedmessage.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tid.protojson.Feedmessage.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tid.protojson.Feedmessage.Entry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          com.tid.protojson.Feedmessage.Entry, Builder> implements com.tid.protojson.Feedmessage.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_Entry_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_Entry_fieldAccessorTable;
      }
      
      // Construct using com.tid.protojson.Feedmessage.Entry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAuthorFieldBuilder();
          getOwnerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (authorBuilder_ == null) {
          author_ = com.tid.protojson.Feedmessage.User.getDefaultInstance();
        } else {
          authorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        link_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        updated_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        publised_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (ownerBuilder_ == null) {
          owner_ = com.tid.protojson.Feedmessage.User.getDefaultInstance();
        } else {
          ownerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tid.protojson.Feedmessage.Entry.getDescriptor();
      }
      
      public com.tid.protojson.Feedmessage.Entry getDefaultInstanceForType() {
        return com.tid.protojson.Feedmessage.Entry.getDefaultInstance();
      }
      
      public com.tid.protojson.Feedmessage.Entry build() {
        com.tid.protojson.Feedmessage.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tid.protojson.Feedmessage.Entry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tid.protojson.Feedmessage.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tid.protojson.Feedmessage.Entry buildPartial() {
        com.tid.protojson.Feedmessage.Entry result = new com.tid.protojson.Feedmessage.Entry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (authorBuilder_ == null) {
          result.author_ = author_;
        } else {
          result.author_ = authorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.link_ = link_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.updated_ = updated_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.publised_ = publised_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (ownerBuilder_ == null) {
          result.owner_ = owner_;
        } else {
          result.owner_ = ownerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tid.protojson.Feedmessage.Entry) {
          return mergeFrom((com.tid.protojson.Feedmessage.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tid.protojson.Feedmessage.Entry other) {
        if (other == com.tid.protojson.Feedmessage.Entry.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAuthor()) {
          mergeAuthor(other.getAuthor());
        }
        if (other.hasLink()) {
          setLink(other.getLink());
        }
        if (other.hasUpdated()) {
          setUpdated(other.getUpdated());
        }
        if (other.hasPublised()) {
          setPublised(other.getPublised());
        }
        if (other.hasOwner()) {
          mergeOwner(other.getOwner());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (hasAuthor()) {
          if (!getAuthor().isInitialized()) {
            
            return false;
          }
        }
        if (hasOwner()) {
          if (!getOwner().isInitialized()) {
            
            return false;
          }
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 34: {
              com.tid.protojson.Feedmessage.User.Builder subBuilder = com.tid.protojson.Feedmessage.User.newBuilder();
              if (hasAuthor()) {
                subBuilder.mergeFrom(getAuthor());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAuthor(subBuilder.buildPartial());
              break;
            }
            case 42: {
              bitField0_ |= 0x00000004;
              link_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              updated_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              publised_ = input.readInt32();
              break;
            }
            case 66: {
              com.tid.protojson.Feedmessage.User.Builder subBuilder = com.tid.protojson.Feedmessage.User.newBuilder();
              if (hasOwner()) {
                subBuilder.mergeFrom(getOwner());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOwner(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 id = 1;
      private int id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getId() {
        return id_;
      }
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }
      
      // optional .com.tid.protojson.User author = 4;
      private com.tid.protojson.Feedmessage.User author_ = com.tid.protojson.Feedmessage.User.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.tid.protojson.Feedmessage.User, com.tid.protojson.Feedmessage.User.Builder, com.tid.protojson.Feedmessage.UserOrBuilder> authorBuilder_;
      public boolean hasAuthor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.tid.protojson.Feedmessage.User getAuthor() {
        if (authorBuilder_ == null) {
          return author_;
        } else {
          return authorBuilder_.getMessage();
        }
      }
      public Builder setAuthor(com.tid.protojson.Feedmessage.User value) {
        if (authorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          author_ = value;
          onChanged();
        } else {
          authorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setAuthor(
          com.tid.protojson.Feedmessage.User.Builder builderForValue) {
        if (authorBuilder_ == null) {
          author_ = builderForValue.build();
          onChanged();
        } else {
          authorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeAuthor(com.tid.protojson.Feedmessage.User value) {
        if (authorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              author_ != com.tid.protojson.Feedmessage.User.getDefaultInstance()) {
            author_ =
              com.tid.protojson.Feedmessage.User.newBuilder(author_).mergeFrom(value).buildPartial();
          } else {
            author_ = value;
          }
          onChanged();
        } else {
          authorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearAuthor() {
        if (authorBuilder_ == null) {
          author_ = com.tid.protojson.Feedmessage.User.getDefaultInstance();
          onChanged();
        } else {
          authorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.tid.protojson.Feedmessage.User.Builder getAuthorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getAuthorFieldBuilder().getBuilder();
      }
      public com.tid.protojson.Feedmessage.UserOrBuilder getAuthorOrBuilder() {
        if (authorBuilder_ != null) {
          return authorBuilder_.getMessageOrBuilder();
        } else {
          return author_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.tid.protojson.Feedmessage.User, com.tid.protojson.Feedmessage.User.Builder, com.tid.protojson.Feedmessage.UserOrBuilder> 
          getAuthorFieldBuilder() {
        if (authorBuilder_ == null) {
          authorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tid.protojson.Feedmessage.User, com.tid.protojson.Feedmessage.User.Builder, com.tid.protojson.Feedmessage.UserOrBuilder>(
                  author_,
                  getParentForChildren(),
                  isClean());
          author_ = null;
        }
        return authorBuilder_;
      }
      
      // optional string link = 5;
      private Object link_ = "";
      public boolean hasLink() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getLink() {
        Object ref = link_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          link_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLink(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        link_ = value;
        onChanged();
        return this;
      }
      public Builder clearLink() {
        bitField0_ = (bitField0_ & ~0x00000004);
        link_ = getDefaultInstance().getLink();
        onChanged();
        return this;
      }
      void setLink(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        link_ = value;
        onChanged();
      }
      
      // optional int32 updated = 6;
      private int updated_ ;
      public boolean hasUpdated() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getUpdated() {
        return updated_;
      }
      public Builder setUpdated(int value) {
        bitField0_ |= 0x00000008;
        updated_ = value;
        onChanged();
        return this;
      }
      public Builder clearUpdated() {
        bitField0_ = (bitField0_ & ~0x00000008);
        updated_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 publised = 7;
      private int publised_ ;
      public boolean hasPublised() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getPublised() {
        return publised_;
      }
      public Builder setPublised(int value) {
        bitField0_ |= 0x00000010;
        publised_ = value;
        onChanged();
        return this;
      }
      public Builder clearPublised() {
        bitField0_ = (bitField0_ & ~0x00000010);
        publised_ = 0;
        onChanged();
        return this;
      }
      
      // optional .com.tid.protojson.User owner = 8;
      private com.tid.protojson.Feedmessage.User owner_ = com.tid.protojson.Feedmessage.User.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.tid.protojson.Feedmessage.User, com.tid.protojson.Feedmessage.User.Builder, com.tid.protojson.Feedmessage.UserOrBuilder> ownerBuilder_;
      public boolean hasOwner() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public com.tid.protojson.Feedmessage.User getOwner() {
        if (ownerBuilder_ == null) {
          return owner_;
        } else {
          return ownerBuilder_.getMessage();
        }
      }
      public Builder setOwner(com.tid.protojson.Feedmessage.User value) {
        if (ownerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          owner_ = value;
          onChanged();
        } else {
          ownerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder setOwner(
          com.tid.protojson.Feedmessage.User.Builder builderForValue) {
        if (ownerBuilder_ == null) {
          owner_ = builderForValue.build();
          onChanged();
        } else {
          ownerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder mergeOwner(com.tid.protojson.Feedmessage.User value) {
        if (ownerBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              owner_ != com.tid.protojson.Feedmessage.User.getDefaultInstance()) {
            owner_ =
              com.tid.protojson.Feedmessage.User.newBuilder(owner_).mergeFrom(value).buildPartial();
          } else {
            owner_ = value;
          }
          onChanged();
        } else {
          ownerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      public Builder clearOwner() {
        if (ownerBuilder_ == null) {
          owner_ = com.tid.protojson.Feedmessage.User.getDefaultInstance();
          onChanged();
        } else {
          ownerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      public com.tid.protojson.Feedmessage.User.Builder getOwnerBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getOwnerFieldBuilder().getBuilder();
      }
      public com.tid.protojson.Feedmessage.UserOrBuilder getOwnerOrBuilder() {
        if (ownerBuilder_ != null) {
          return ownerBuilder_.getMessageOrBuilder();
        } else {
          return owner_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.tid.protojson.Feedmessage.User, com.tid.protojson.Feedmessage.User.Builder, com.tid.protojson.Feedmessage.UserOrBuilder> 
          getOwnerFieldBuilder() {
        if (ownerBuilder_ == null) {
          ownerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.tid.protojson.Feedmessage.User, com.tid.protojson.Feedmessage.User.Builder, com.tid.protojson.Feedmessage.UserOrBuilder>(
                  owner_,
                  getParentForChildren(),
                  isClean());
          owner_ = null;
        }
        return ownerBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:com.tid.protojson.Entry)
    }
    
    static {
      defaultInstance = new Entry(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.tid.protojson.Entry)
  }
  
  public interface FeedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string id = 1;
    boolean hasId();
    String getId();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // repeated .com.tid.protojson.Entry entry = 3;
    java.util.List<com.tid.protojson.Feedmessage.Entry> 
        getEntryList();
    com.tid.protojson.Feedmessage.Entry getEntry(int index);
    int getEntryCount();
    java.util.List<? extends com.tid.protojson.Feedmessage.EntryOrBuilder> 
        getEntryOrBuilderList();
    com.tid.protojson.Feedmessage.EntryOrBuilder getEntryOrBuilder(
        int index);
    
    // optional int32 version = 4 [default = 3];
    boolean hasVersion();
    int getVersion();
  }
  public static final class Feed extends
      com.google.protobuf.GeneratedMessage
      implements FeedOrBuilder {
    // Use Feed.newBuilder() to construct.
    private Feed(Builder builder) {
      super(builder);
    }
    private Feed(boolean noInit) {}
    
    private static final Feed defaultInstance;
    public static Feed getDefaultInstance() {
      return defaultInstance;
    }
    
    public Feed getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_Feed_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_Feed_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .com.tid.protojson.Entry entry = 3;
    public static final int ENTRY_FIELD_NUMBER = 3;
    private java.util.List<com.tid.protojson.Feedmessage.Entry> entry_;
    public java.util.List<com.tid.protojson.Feedmessage.Entry> getEntryList() {
      return entry_;
    }
    public java.util.List<? extends com.tid.protojson.Feedmessage.EntryOrBuilder> 
        getEntryOrBuilderList() {
      return entry_;
    }
    public int getEntryCount() {
      return entry_.size();
    }
    public com.tid.protojson.Feedmessage.Entry getEntry(int index) {
      return entry_.get(index);
    }
    public com.tid.protojson.Feedmessage.EntryOrBuilder getEntryOrBuilder(
        int index) {
      return entry_.get(index);
    }
    
    // optional int32 version = 4 [default = 3];
    public static final int VERSION_FIELD_NUMBER = 4;
    private int version_;
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getVersion() {
      return version_;
    }
    
    private void initFields() {
      id_ = "";
      title_ = "";
      entry_ = java.util.Collections.emptyList();
      version_ = 3;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getEntryCount(); i++) {
        if (!getEntry(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      for (int i = 0; i < entry_.size(); i++) {
        output.writeMessage(3, entry_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, version_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      for (int i = 0; i < entry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, entry_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, version_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tid.protojson.Feedmessage.Feed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Feed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Feed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Feed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Feed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Feed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Feed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tid.protojson.Feedmessage.Feed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tid.protojson.Feedmessage.Feed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tid.protojson.Feedmessage.Feed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tid.protojson.Feedmessage.Feed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tid.protojson.Feedmessage.FeedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_Feed_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tid.protojson.Feedmessage.internal_static_com_tid_protojson_Feed_fieldAccessorTable;
      }
      
      // Construct using com.tid.protojson.Feedmessage.Feed.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEntryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          entryBuilder_.clear();
        }
        version_ = 3;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tid.protojson.Feedmessage.Feed.getDescriptor();
      }
      
      public com.tid.protojson.Feedmessage.Feed getDefaultInstanceForType() {
        return com.tid.protojson.Feedmessage.Feed.getDefaultInstance();
      }
      
      public com.tid.protojson.Feedmessage.Feed build() {
        com.tid.protojson.Feedmessage.Feed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tid.protojson.Feedmessage.Feed buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tid.protojson.Feedmessage.Feed result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tid.protojson.Feedmessage.Feed buildPartial() {
        com.tid.protojson.Feedmessage.Feed result = new com.tid.protojson.Feedmessage.Feed(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (entryBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            entry_ = java.util.Collections.unmodifiableList(entry_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.entry_ = entry_;
        } else {
          result.entry_ = entryBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.version_ = version_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tid.protojson.Feedmessage.Feed) {
          return mergeFrom((com.tid.protojson.Feedmessage.Feed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tid.protojson.Feedmessage.Feed other) {
        if (other == com.tid.protojson.Feedmessage.Feed.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (entryBuilder_ == null) {
          if (!other.entry_.isEmpty()) {
            if (entry_.isEmpty()) {
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureEntryIsMutable();
              entry_.addAll(other.entry_);
            }
            onChanged();
          }
        } else {
          if (!other.entry_.isEmpty()) {
            if (entryBuilder_.isEmpty()) {
              entryBuilder_.dispose();
              entryBuilder_ = null;
              entry_ = other.entry_;
              bitField0_ = (bitField0_ & ~0x00000004);
              entryBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEntryFieldBuilder() : null;
            } else {
              entryBuilder_.addAllMessages(other.entry_);
            }
          }
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getEntryCount(); i++) {
          if (!getEntry(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              com.tid.protojson.Feedmessage.Entry.Builder subBuilder = com.tid.protojson.Feedmessage.Entry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntry(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              version_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string id = 1;
      private Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // optional string title = 2;
      private Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // repeated .com.tid.protojson.Entry entry = 3;
      private java.util.List<com.tid.protojson.Feedmessage.Entry> entry_ =
        java.util.Collections.emptyList();
      private void ensureEntryIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          entry_ = new java.util.ArrayList<com.tid.protojson.Feedmessage.Entry>(entry_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tid.protojson.Feedmessage.Entry, com.tid.protojson.Feedmessage.Entry.Builder, com.tid.protojson.Feedmessage.EntryOrBuilder> entryBuilder_;
      
      public java.util.List<com.tid.protojson.Feedmessage.Entry> getEntryList() {
        if (entryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entry_);
        } else {
          return entryBuilder_.getMessageList();
        }
      }
      public int getEntryCount() {
        if (entryBuilder_ == null) {
          return entry_.size();
        } else {
          return entryBuilder_.getCount();
        }
      }
      public com.tid.protojson.Feedmessage.Entry getEntry(int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);
        } else {
          return entryBuilder_.getMessage(index);
        }
      }
      public Builder setEntry(
          int index, com.tid.protojson.Feedmessage.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.set(index, value);
          onChanged();
        } else {
          entryBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setEntry(
          int index, com.tid.protojson.Feedmessage.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.set(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addEntry(com.tid.protojson.Feedmessage.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(value);
          onChanged();
        } else {
          entryBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addEntry(
          int index, com.tid.protojson.Feedmessage.Entry value) {
        if (entryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntryIsMutable();
          entry_.add(index, value);
          onChanged();
        } else {
          entryBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addEntry(
          com.tid.protojson.Feedmessage.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addEntry(
          int index, com.tid.protojson.Feedmessage.Entry.Builder builderForValue) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.add(index, builderForValue.build());
          onChanged();
        } else {
          entryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllEntry(
          java.lang.Iterable<? extends com.tid.protojson.Feedmessage.Entry> values) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          super.addAll(values, entry_);
          onChanged();
        } else {
          entryBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearEntry() {
        if (entryBuilder_ == null) {
          entry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          entryBuilder_.clear();
        }
        return this;
      }
      public Builder removeEntry(int index) {
        if (entryBuilder_ == null) {
          ensureEntryIsMutable();
          entry_.remove(index);
          onChanged();
        } else {
          entryBuilder_.remove(index);
        }
        return this;
      }
      public com.tid.protojson.Feedmessage.Entry.Builder getEntryBuilder(
          int index) {
        return getEntryFieldBuilder().getBuilder(index);
      }
      public com.tid.protojson.Feedmessage.EntryOrBuilder getEntryOrBuilder(
          int index) {
        if (entryBuilder_ == null) {
          return entry_.get(index);  } else {
          return entryBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.tid.protojson.Feedmessage.EntryOrBuilder> 
           getEntryOrBuilderList() {
        if (entryBuilder_ != null) {
          return entryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entry_);
        }
      }
      public com.tid.protojson.Feedmessage.Entry.Builder addEntryBuilder() {
        return getEntryFieldBuilder().addBuilder(
            com.tid.protojson.Feedmessage.Entry.getDefaultInstance());
      }
      public com.tid.protojson.Feedmessage.Entry.Builder addEntryBuilder(
          int index) {
        return getEntryFieldBuilder().addBuilder(
            index, com.tid.protojson.Feedmessage.Entry.getDefaultInstance());
      }
      public java.util.List<com.tid.protojson.Feedmessage.Entry.Builder> 
           getEntryBuilderList() {
        return getEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tid.protojson.Feedmessage.Entry, com.tid.protojson.Feedmessage.Entry.Builder, com.tid.protojson.Feedmessage.EntryOrBuilder> 
          getEntryFieldBuilder() {
        if (entryBuilder_ == null) {
          entryBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.tid.protojson.Feedmessage.Entry, com.tid.protojson.Feedmessage.Entry.Builder, com.tid.protojson.Feedmessage.EntryOrBuilder>(
                  entry_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          entry_ = null;
        }
        return entryBuilder_;
      }
      
      // optional int32 version = 4 [default = 3];
      private int version_ = 3;
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getVersion() {
        return version_;
      }
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000008;
        version_ = value;
        onChanged();
        return this;
      }
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 3;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.tid.protojson.Feed)
    }
    
    static {
      defaultInstance = new Feed(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.tid.protojson.Feed)
  }
  
  public static final int SOURCE_FIELD_NUMBER = 10;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.String> source = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int D_FIELD_NUMBER = 11;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Double> d = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Double.class,
        null);
  public static final int F_FIELD_NUMBER = 12;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Float> f = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Float.class,
        null);
  public static final int I32_FIELD_NUMBER = 13;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Integer> i32 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int I64_FIELD_NUMBER = 14;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Long> i64 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int UI32_FIELD_NUMBER = 15;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Integer> ui32 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int UI64_FIELD_NUMBER = 16;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Long> ui64 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int SI32_FIELD_NUMBER = 17;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Integer> si32 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int SI64_FIELD_NUMBER = 18;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Long> si64 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int F32_FIELD_NUMBER = 19;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Integer> f32 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int F64_FIELD_NUMBER = 20;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Long> f64 = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Long.class,
        null);
  public static final int VERDAD_FIELD_NUMBER = 21;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.Boolean> verdad = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int S_FIELD_NUMBER = 22;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      java.lang.String> s = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int BITES_FIELD_NUMBER = 23;
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.tid.protojson.Feedmessage.Entry,
      com.google.protobuf.ByteString> bites = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.protobuf.ByteString.class,
        null);
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tid_protojson_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tid_protojson_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tid_protojson_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tid_protojson_Entry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tid_protojson_Feed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tid_protojson_Feed_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021feedmessage.proto\022\021com.tid.protojson\"4" +
      "\n\004User\022\014\n\004uuid\030\001 \002(\t\022\016\n\006domain\030\002 \002(\t\022\016\n\006" +
      "number\030\010 \001(\005\"\241\001\n\005Entry\022\n\n\002id\030\001 \002(\005\022\'\n\006au" +
      "thor\030\004 \001(\0132\027.com.tid.protojson.User\022\014\n\004l" +
      "ink\030\005 \001(\t\022\017\n\007updated\030\006 \001(\005\022\020\n\010publised\030\007" +
      " \001(\005\022&\n\005owner\030\010 \001(\0132\027.com.tid.protojson." +
      "User*\004\010\n\020\025*\004\010\025\020\037\"^\n\004Feed\022\n\n\002id\030\001 \001(\t\022\r\n\005" +
      "title\030\002 \001(\t\022\'\n\005entry\030\003 \003(\0132\030.com.tid.pro" +
      "tojson.Entry\022\022\n\007version\030\004 \001(\005:\0013:(\n\006sour" +
      "ce\022\030.com.tid.protojson.Entry\030\n \001(\t:#\n\001d\022",
      "\030.com.tid.protojson.Entry\030\013 \001(\001:#\n\001f\022\030.c" +
      "om.tid.protojson.Entry\030\014 \001(\002:%\n\003i32\022\030.co" +
      "m.tid.protojson.Entry\030\r \001(\005:%\n\003i64\022\030.com" +
      ".tid.protojson.Entry\030\016 \001(\003:&\n\004ui32\022\030.com" +
      ".tid.protojson.Entry\030\017 \001(\r:&\n\004ui64\022\030.com" +
      ".tid.protojson.Entry\030\020 \001(\004:&\n\004si32\022\030.com" +
      ".tid.protojson.Entry\030\021 \001(\021:&\n\004si64\022\030.com" +
      ".tid.protojson.Entry\030\022 \001(\022:%\n\003f32\022\030.com." +
      "tid.protojson.Entry\030\023 \001(\007:%\n\003f64\022\030.com.t" +
      "id.protojson.Entry\030\024 \001(\006:(\n\006verdad\022\030.com",
      ".tid.protojson.Entry\030\025 \001(\010:#\n\001s\022\030.com.ti" +
      "d.protojson.Entry\030\026 \001(\t:\'\n\005bites\022\030.com.t" +
      "id.protojson.Entry\030\027 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_tid_protojson_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_tid_protojson_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tid_protojson_User_descriptor,
              new java.lang.String[] { "Uuid", "Domain", "Number", },
              com.tid.protojson.Feedmessage.User.class,
              com.tid.protojson.Feedmessage.User.Builder.class);
          internal_static_com_tid_protojson_Entry_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_tid_protojson_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tid_protojson_Entry_descriptor,
              new java.lang.String[] { "Id", "Author", "Link", "Updated", "Publised", "Owner", },
              com.tid.protojson.Feedmessage.Entry.class,
              com.tid.protojson.Feedmessage.Entry.Builder.class);
          internal_static_com_tid_protojson_Feed_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_tid_protojson_Feed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tid_protojson_Feed_descriptor,
              new java.lang.String[] { "Id", "Title", "Entry", "Version", },
              com.tid.protojson.Feedmessage.Feed.class,
              com.tid.protojson.Feedmessage.Feed.Builder.class);
          source.internalInit(descriptor.getExtensions().get(0));
          d.internalInit(descriptor.getExtensions().get(1));
          f.internalInit(descriptor.getExtensions().get(2));
          i32.internalInit(descriptor.getExtensions().get(3));
          i64.internalInit(descriptor.getExtensions().get(4));
          ui32.internalInit(descriptor.getExtensions().get(5));
          ui64.internalInit(descriptor.getExtensions().get(6));
          si32.internalInit(descriptor.getExtensions().get(7));
          si64.internalInit(descriptor.getExtensions().get(8));
          f32.internalInit(descriptor.getExtensions().get(9));
          f64.internalInit(descriptor.getExtensions().get(10));
          verdad.internalInit(descriptor.getExtensions().get(11));
          s.internalInit(descriptor.getExtensions().get(12));
          bites.internalInit(descriptor.getExtensions().get(13));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
