// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feedmessage.proto

public final class Feedmessage {
  private Feedmessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class User extends
      com.google.protobuf.GeneratedMessage {
    // Use User.newBuilder() to construct.
    private User() {
      initFields();
    }
    private User(boolean noInit) {}
    
    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }
    
    public User getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Feedmessage.internal_static_User_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Feedmessage.internal_static_User_fieldAccessorTable;
    }
    
    // required string uuid = 1;
    public static final int UUID_FIELD_NUMBER = 1;
    private boolean hasUuid;
    private java.lang.String uuid_ = "";
    public boolean hasUuid() { return hasUuid; }
    public java.lang.String getUuid() { return uuid_; }
    
    // required string domain = 2;
    public static final int DOMAIN_FIELD_NUMBER = 2;
    private boolean hasDomain;
    private java.lang.String domain_ = "";
    public boolean hasDomain() { return hasDomain; }
    public java.lang.String getDomain() { return domain_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasUuid) return false;
      if (!hasDomain) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasUuid()) {
        output.writeString(1, getUuid());
      }
      if (hasDomain()) {
        output.writeString(2, getDomain());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasUuid()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getUuid());
      }
      if (hasDomain()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getDomain());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Feedmessage.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Feedmessage.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Feedmessage.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Feedmessage.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Feedmessage.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Feedmessage.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Feedmessage.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Feedmessage.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private Feedmessage.User result;
      
      // Construct using Feedmessage.User.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Feedmessage.User();
        return builder;
      }
      
      protected Feedmessage.User internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Feedmessage.User();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Feedmessage.User.getDescriptor();
      }
      
      public Feedmessage.User getDefaultInstanceForType() {
        return Feedmessage.User.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Feedmessage.User build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Feedmessage.User buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Feedmessage.User buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        Feedmessage.User returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Feedmessage.User) {
          return mergeFrom((Feedmessage.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Feedmessage.User other) {
        if (other == Feedmessage.User.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasDomain()) {
          setDomain(other.getDomain());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setUuid(input.readString());
              break;
            }
            case 18: {
              setDomain(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string uuid = 1;
      public boolean hasUuid() {
        return result.hasUuid();
      }
      public java.lang.String getUuid() {
        return result.getUuid();
      }
      public Builder setUuid(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUuid = true;
        result.uuid_ = value;
        return this;
      }
      public Builder clearUuid() {
        result.hasUuid = false;
        result.uuid_ = getDefaultInstance().getUuid();
        return this;
      }
      
      // required string domain = 2;
      public boolean hasDomain() {
        return result.hasDomain();
      }
      public java.lang.String getDomain() {
        return result.getDomain();
      }
      public Builder setDomain(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDomain = true;
        result.domain_ = value;
        return this;
      }
      public Builder clearDomain() {
        result.hasDomain = false;
        result.domain_ = getDefaultInstance().getDomain();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:User)
    }
    
    static {
      defaultInstance = new User(true);
      Feedmessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:User)
  }
  
  public static final class Entry extends
      com.google.protobuf.GeneratedMessage {
    // Use Entry.newBuilder() to construct.
    private Entry() {
      initFields();
    }
    private Entry(boolean noInit) {}
    
    private static final Entry defaultInstance;
    public static Entry getDefaultInstance() {
      return defaultInstance;
    }
    
    public Entry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Feedmessage.internal_static_Entry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Feedmessage.internal_static_Entry_fieldAccessorTable;
    }
    
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private java.lang.String id_ = "";
    public boolean hasId() { return hasId; }
    public java.lang.String getId() { return id_; }
    
    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // required string summary = 3;
    public static final int SUMMARY_FIELD_NUMBER = 3;
    private boolean hasSummary;
    private java.lang.String summary_ = "";
    public boolean hasSummary() { return hasSummary; }
    public java.lang.String getSummary() { return summary_; }
    
    // optional .User author = 4;
    public static final int AUTHOR_FIELD_NUMBER = 4;
    private boolean hasAuthor;
    private Feedmessage.User author_;
    public boolean hasAuthor() { return hasAuthor; }
    public Feedmessage.User getAuthor() { return author_; }
    
    // optional string link = 5;
    public static final int LINK_FIELD_NUMBER = 5;
    private boolean hasLink;
    private java.lang.String link_ = "";
    public boolean hasLink() { return hasLink; }
    public java.lang.String getLink() { return link_; }
    
    // optional int32 updated = 6;
    public static final int UPDATED_FIELD_NUMBER = 6;
    private boolean hasUpdated;
    private int updated_ = 0;
    public boolean hasUpdated() { return hasUpdated; }
    public int getUpdated() { return updated_; }
    
    // optional int32 publised = 7;
    public static final int PUBLISED_FIELD_NUMBER = 7;
    private boolean hasPublised;
    private int publised_ = 0;
    public boolean hasPublised() { return hasPublised; }
    public int getPublised() { return publised_; }
    
    // optional .User owner = 8;
    public static final int OWNER_FIELD_NUMBER = 8;
    private boolean hasOwner;
    private Feedmessage.User owner_;
    public boolean hasOwner() { return hasOwner; }
    public Feedmessage.User getOwner() { return owner_; }
    
    private void initFields() {
      author_ = Feedmessage.User.getDefaultInstance();
      owner_ = Feedmessage.User.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasTitle) return false;
      if (!hasSummary) return false;
      if (hasAuthor()) {
        if (!getAuthor().isInitialized()) return false;
      }
      if (hasOwner()) {
        if (!getOwner().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeString(1, getId());
      }
      if (hasTitle()) {
        output.writeString(2, getTitle());
      }
      if (hasSummary()) {
        output.writeString(3, getSummary());
      }
      if (hasAuthor()) {
        output.writeMessage(4, getAuthor());
      }
      if (hasLink()) {
        output.writeString(5, getLink());
      }
      if (hasUpdated()) {
        output.writeInt32(6, getUpdated());
      }
      if (hasPublised()) {
        output.writeInt32(7, getPublised());
      }
      if (hasOwner()) {
        output.writeMessage(8, getOwner());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getId());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTitle());
      }
      if (hasSummary()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSummary());
      }
      if (hasAuthor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAuthor());
      }
      if (hasLink()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getLink());
      }
      if (hasUpdated()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getUpdated());
      }
      if (hasPublised()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, getPublised());
      }
      if (hasOwner()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getOwner());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Feedmessage.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Feedmessage.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Feedmessage.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Feedmessage.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Feedmessage.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Feedmessage.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Feedmessage.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Feedmessage.Entry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private Feedmessage.Entry result;
      
      // Construct using Feedmessage.Entry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Feedmessage.Entry();
        return builder;
      }
      
      protected Feedmessage.Entry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Feedmessage.Entry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Feedmessage.Entry.getDescriptor();
      }
      
      public Feedmessage.Entry getDefaultInstanceForType() {
        return Feedmessage.Entry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Feedmessage.Entry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Feedmessage.Entry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Feedmessage.Entry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        Feedmessage.Entry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Feedmessage.Entry) {
          return mergeFrom((Feedmessage.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Feedmessage.Entry other) {
        if (other == Feedmessage.Entry.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasSummary()) {
          setSummary(other.getSummary());
        }
        if (other.hasAuthor()) {
          mergeAuthor(other.getAuthor());
        }
        if (other.hasLink()) {
          setLink(other.getLink());
        }
        if (other.hasUpdated()) {
          setUpdated(other.getUpdated());
        }
        if (other.hasPublised()) {
          setPublised(other.getPublised());
        }
        if (other.hasOwner()) {
          mergeOwner(other.getOwner());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setId(input.readString());
              break;
            }
            case 18: {
              setTitle(input.readString());
              break;
            }
            case 26: {
              setSummary(input.readString());
              break;
            }
            case 34: {
              Feedmessage.User.Builder subBuilder = Feedmessage.User.newBuilder();
              if (hasAuthor()) {
                subBuilder.mergeFrom(getAuthor());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setAuthor(subBuilder.buildPartial());
              break;
            }
            case 42: {
              setLink(input.readString());
              break;
            }
            case 48: {
              setUpdated(input.readInt32());
              break;
            }
            case 56: {
              setPublised(input.readInt32());
              break;
            }
            case 66: {
              Feedmessage.User.Builder subBuilder = Feedmessage.User.newBuilder();
              if (hasOwner()) {
                subBuilder.mergeFrom(getOwner());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOwner(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public java.lang.String getId() {
        return result.getId();
      }
      public Builder setId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = getDefaultInstance().getId();
        return this;
      }
      
      // required string title = 2;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // required string summary = 3;
      public boolean hasSummary() {
        return result.hasSummary();
      }
      public java.lang.String getSummary() {
        return result.getSummary();
      }
      public Builder setSummary(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSummary = true;
        result.summary_ = value;
        return this;
      }
      public Builder clearSummary() {
        result.hasSummary = false;
        result.summary_ = getDefaultInstance().getSummary();
        return this;
      }
      
      // optional .User author = 4;
      public boolean hasAuthor() {
        return result.hasAuthor();
      }
      public Feedmessage.User getAuthor() {
        return result.getAuthor();
      }
      public Builder setAuthor(Feedmessage.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasAuthor = true;
        result.author_ = value;
        return this;
      }
      public Builder setAuthor(Feedmessage.User.Builder builderForValue) {
        result.hasAuthor = true;
        result.author_ = builderForValue.build();
        return this;
      }
      public Builder mergeAuthor(Feedmessage.User value) {
        if (result.hasAuthor() &&
            result.author_ != Feedmessage.User.getDefaultInstance()) {
          result.author_ =
            Feedmessage.User.newBuilder(result.author_).mergeFrom(value).buildPartial();
        } else {
          result.author_ = value;
        }
        result.hasAuthor = true;
        return this;
      }
      public Builder clearAuthor() {
        result.hasAuthor = false;
        result.author_ = Feedmessage.User.getDefaultInstance();
        return this;
      }
      
      // optional string link = 5;
      public boolean hasLink() {
        return result.hasLink();
      }
      public java.lang.String getLink() {
        return result.getLink();
      }
      public Builder setLink(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLink = true;
        result.link_ = value;
        return this;
      }
      public Builder clearLink() {
        result.hasLink = false;
        result.link_ = getDefaultInstance().getLink();
        return this;
      }
      
      // optional int32 updated = 6;
      public boolean hasUpdated() {
        return result.hasUpdated();
      }
      public int getUpdated() {
        return result.getUpdated();
      }
      public Builder setUpdated(int value) {
        result.hasUpdated = true;
        result.updated_ = value;
        return this;
      }
      public Builder clearUpdated() {
        result.hasUpdated = false;
        result.updated_ = 0;
        return this;
      }
      
      // optional int32 publised = 7;
      public boolean hasPublised() {
        return result.hasPublised();
      }
      public int getPublised() {
        return result.getPublised();
      }
      public Builder setPublised(int value) {
        result.hasPublised = true;
        result.publised_ = value;
        return this;
      }
      public Builder clearPublised() {
        result.hasPublised = false;
        result.publised_ = 0;
        return this;
      }
      
      // optional .User owner = 8;
      public boolean hasOwner() {
        return result.hasOwner();
      }
      public Feedmessage.User getOwner() {
        return result.getOwner();
      }
      public Builder setOwner(Feedmessage.User value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasOwner = true;
        result.owner_ = value;
        return this;
      }
      public Builder setOwner(Feedmessage.User.Builder builderForValue) {
        result.hasOwner = true;
        result.owner_ = builderForValue.build();
        return this;
      }
      public Builder mergeOwner(Feedmessage.User value) {
        if (result.hasOwner() &&
            result.owner_ != Feedmessage.User.getDefaultInstance()) {
          result.owner_ =
            Feedmessage.User.newBuilder(result.owner_).mergeFrom(value).buildPartial();
        } else {
          result.owner_ = value;
        }
        result.hasOwner = true;
        return this;
      }
      public Builder clearOwner() {
        result.hasOwner = false;
        result.owner_ = Feedmessage.User.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Entry)
    }
    
    static {
      defaultInstance = new Entry(true);
      Feedmessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Entry)
  }
  
  public static final class Feed extends
      com.google.protobuf.GeneratedMessage {
    // Use Feed.newBuilder() to construct.
    private Feed() {
      initFields();
    }
    private Feed(boolean noInit) {}
    
    private static final Feed defaultInstance;
    public static Feed getDefaultInstance() {
      return defaultInstance;
    }
    
    public Feed getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Feedmessage.internal_static_Feed_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Feedmessage.internal_static_Feed_fieldAccessorTable;
    }
    
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private java.lang.String id_ = "";
    public boolean hasId() { return hasId; }
    public java.lang.String getId() { return id_; }
    
    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // repeated .Entry entry = 3;
    public static final int ENTRY_FIELD_NUMBER = 3;
    private java.util.List<Feedmessage.Entry> entry_ =
      java.util.Collections.emptyList();
    public java.util.List<Feedmessage.Entry> getEntryList() {
      return entry_;
    }
    public int getEntryCount() { return entry_.size(); }
    public Feedmessage.Entry getEntry(int index) {
      return entry_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasId) return false;
      if (!hasTitle) return false;
      for (Feedmessage.Entry element : getEntryList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeString(1, getId());
      }
      if (hasTitle()) {
        output.writeString(2, getTitle());
      }
      for (Feedmessage.Entry element : getEntryList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getId());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getTitle());
      }
      for (Feedmessage.Entry element : getEntryList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static Feedmessage.Feed parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Feedmessage.Feed parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.Feed parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Feedmessage.Feed parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.Feed parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Feedmessage.Feed parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Feedmessage.Feed parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Feedmessage.Feed parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Feedmessage.Feed parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Feedmessage.Feed parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Feedmessage.Feed prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private Feedmessage.Feed result;
      
      // Construct using Feedmessage.Feed.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new Feedmessage.Feed();
        return builder;
      }
      
      protected Feedmessage.Feed internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new Feedmessage.Feed();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Feedmessage.Feed.getDescriptor();
      }
      
      public Feedmessage.Feed getDefaultInstanceForType() {
        return Feedmessage.Feed.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public Feedmessage.Feed build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private Feedmessage.Feed buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public Feedmessage.Feed buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.entry_ != java.util.Collections.EMPTY_LIST) {
          result.entry_ =
            java.util.Collections.unmodifiableList(result.entry_);
        }
        Feedmessage.Feed returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Feedmessage.Feed) {
          return mergeFrom((Feedmessage.Feed)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Feedmessage.Feed other) {
        if (other == Feedmessage.Feed.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (!other.entry_.isEmpty()) {
          if (result.entry_.isEmpty()) {
            result.entry_ = new java.util.ArrayList<Feedmessage.Entry>();
          }
          result.entry_.addAll(other.entry_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setId(input.readString());
              break;
            }
            case 18: {
              setTitle(input.readString());
              break;
            }
            case 26: {
              Feedmessage.Entry.Builder subBuilder = Feedmessage.Entry.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEntry(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required string id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public java.lang.String getId() {
        return result.getId();
      }
      public Builder setId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = getDefaultInstance().getId();
        return this;
      }
      
      // required string title = 2;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // repeated .Entry entry = 3;
      public java.util.List<Feedmessage.Entry> getEntryList() {
        return java.util.Collections.unmodifiableList(result.entry_);
      }
      public int getEntryCount() {
        return result.getEntryCount();
      }
      public Feedmessage.Entry getEntry(int index) {
        return result.getEntry(index);
      }
      public Builder setEntry(int index, Feedmessage.Entry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.entry_.set(index, value);
        return this;
      }
      public Builder setEntry(int index, Feedmessage.Entry.Builder builderForValue) {
        result.entry_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEntry(Feedmessage.Entry value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.entry_.isEmpty()) {
          result.entry_ = new java.util.ArrayList<Feedmessage.Entry>();
        }
        result.entry_.add(value);
        return this;
      }
      public Builder addEntry(Feedmessage.Entry.Builder builderForValue) {
        if (result.entry_.isEmpty()) {
          result.entry_ = new java.util.ArrayList<Feedmessage.Entry>();
        }
        result.entry_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEntry(
          java.lang.Iterable<? extends Feedmessage.Entry> values) {
        if (result.entry_.isEmpty()) {
          result.entry_ = new java.util.ArrayList<Feedmessage.Entry>();
        }
        super.addAll(values, result.entry_);
        return this;
      }
      public Builder clearEntry() {
        result.entry_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Feed)
    }
    
    static {
      defaultInstance = new Feed(true);
      Feedmessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Feed)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Entry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Entry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Feed_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Feed_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021feedmessage.proto\"$\n\004User\022\014\n\004uuid\030\001 \002(" +
      "\t\022\016\n\006domain\030\002 \002(\t\"\221\001\n\005Entry\022\n\n\002id\030\001 \002(\t\022" +
      "\r\n\005title\030\002 \002(\t\022\017\n\007summary\030\003 \002(\t\022\025\n\006autho" +
      "r\030\004 \001(\0132\005.User\022\014\n\004link\030\005 \001(\t\022\017\n\007updated\030" +
      "\006 \001(\005\022\020\n\010publised\030\007 \001(\005\022\024\n\005owner\030\010 \001(\0132\005" +
      ".User\"8\n\004Feed\022\n\n\002id\030\001 \002(\t\022\r\n\005title\030\002 \002(\t" +
      "\022\025\n\005entry\030\003 \003(\0132\006.Entry"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_User_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_User_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_User_descriptor,
              new java.lang.String[] { "Uuid", "Domain", },
              Feedmessage.User.class,
              Feedmessage.User.Builder.class);
          internal_static_Entry_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Entry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Entry_descriptor,
              new java.lang.String[] { "Id", "Title", "Summary", "Author", "Link", "Updated", "Publised", "Owner", },
              Feedmessage.Entry.class,
              Feedmessage.Entry.Builder.class);
          internal_static_Feed_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Feed_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Feed_descriptor,
              new java.lang.String[] { "Id", "Title", "Entry", },
              Feedmessage.Feed.class,
              Feedmessage.Feed.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
